plugins {
    id "com.android.application"
}

dependencies {
    implementation "com.google.mlkit:text-recognition:16.0.1"
}

android {
    namespace "com.ghostly.apk"
    compileSdk 35

    defaultConfig {
        applicationId "com.ghostly.apk"
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName "0.7.0"
    }
}
